services:
  #Our postgresSQL database
  db:
    # The Docker image of postgres
    image: postgres:latest
    # The ports to expose to the host container
    # 5432 is the default PostgresSQL port
    ports:
        - "5432:5432"
      # If we accidently kill the contaier, Docker compose
      # will restart it
    restart: always
      # PostgresSQL Docker container uses environment variables to
      # read configuration, here we set the password
      # - DO NOT STORE PLAINTEXT PASSWORDS in source control.
      # We do so here as this is a builder

    environment:
      POSTGRES_PASSWORD: changemeinprod!